#!/usr/bin/env bash
# Copyright (c) 2026, Shanghai Iluvatar CoreX Semiconductor Co., Ltd.
# SPDX-License-Identifier: Apache-2.0

# Shared defaults for aggregated vLLM + LMCache MP + Mooncake Store L2.
#
# Every requester host must use the same tenant, chunk size, hash seed, model,
# TP size, and KV layout. Host/IP and RDMA device values are intentionally
# supplied by the operator for each machine or Pod.

export NO_PROXY="127.0.0.1,localhost,::1${NO_PROXY:+,${NO_PROXY}}"
export no_proxy="127.0.0.1,localhost,::1${no_proxy:+,${no_proxy}}"

export PYTHONHASHSEED="${PYTHONHASHSEED:-42}"
export VLLM_KV_CACHE_LAYOUT="${VLLM_KV_CACHE_LAYOUT:-HND}"
export VLLM_KV_DISABLE_CROSS_GROUP_SHARE="${VLLM_KV_DISABLE_CROSS_GROUP_SHARE:-1}"
export NCCL_CUMEM_ENABLE="${NCCL_CUMEM_ENABLE:-0}"
export VLLM_SKIP_P2P_CHECK="${VLLM_SKIP_P2P_CHECK:-1}"

export MODEL_PATH="${MODEL_PATH:-/data/nlp/Qwen3.5-27B-W8A8-fixed}"
export SERVED_MODEL_NAME="${SERVED_MODEL_NAME:-Qwen3.5-27B-W8A8-fixed}"
export TENSOR_PARALLEL="${TENSOR_PARALLEL:-2}"
export GPU_MEM_UTIL="${GPU_MEM_UTIL:-0.90}"
export MAX_MODEL_LEN="${MAX_MODEL_LEN:-131072}"
export MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-1024}"
export SERVER_HOST="${SERVER_HOST:-0.0.0.0}"
export SERVER_PORT="${SERVER_PORT:-18040}"

export LMCACHE_MP_PORT="${LMCACHE_MP_PORT:-6585}"
export LMCACHE_HTTP_PORT="${LMCACHE_HTTP_PORT:-8100}"
export LMCACHE_URL="${LMCACHE_URL:-http://127.0.0.1:${LMCACHE_HTTP_PORT}}"
export LMCACHE_MP_SERVER_URL="${LMCACHE_MP_SERVER_URL:-tcp://127.0.0.1:${LMCACHE_MP_PORT}}"
export LMCACHE_CHUNK_SIZE="${LMCACHE_CHUNK_SIZE:-784}"
export LMCACHE_L1_SIZE_GB="${LMCACHE_L1_SIZE_GB:-16}"
export LMCACHE_MAX_WORKERS="${LMCACHE_MAX_WORKERS:-$((2 * TENSOR_PARALLEL))}"
export LMCACHE_L2_PREFETCH_MAX_IN_FLIGHT="${LMCACHE_L2_PREFETCH_MAX_IN_FLIGHT:-8}"
export LMCACHE_L2_NUM_WORKERS="${LMCACHE_L2_NUM_WORKERS:-8}"
export LMCACHE_LOCAL_BUFFER_SIZE="${LMCACHE_LOCAL_BUFFER_SIZE:-1073741824}"

export MOONCAKE_PROTOCOL="${MOONCAKE_PROTOCOL:-tcp}"
export MOONCAKE_MASTER_ADDR="${MOONCAKE_MASTER_ADDR:-127.0.0.1:50051}"
export MOONCAKE_MASTER_PORT="${MOONCAKE_MASTER_PORT:-50051}"
export MOONCAKE_MASTER_METRICS_PORT="${MOONCAKE_MASTER_METRICS_PORT:-9003}"
export MOONCAKE_METADATA_SERVER="${MOONCAKE_METADATA_SERVER:-P2PHANDSHAKE}"
export MOONCAKE_TENANT_ID="${MOONCAKE_TENANT_ID:-lmcache-iluvatar-mooncake-l2-example}"
export MOONCAKE_RDMA_DEVICES="${MOONCAKE_RDMA_DEVICES:-}"

# Required by start_mooncake_store.sh on each Store host/Pod.
export MOONCAKE_STORE_HOST="${MOONCAKE_STORE_HOST:-}"
export MOONCAKE_STORE_PORT="${MOONCAKE_STORE_PORT:-50052}"
export MOONCAKE_STORE_HTTP_PORT="${MOONCAKE_STORE_HTTP_PORT:-9300}"
export MOONCAKE_STORE_SIZE="${MOONCAKE_STORE_SIZE:-32GB}"
export MOONCAKE_STORE_THREADS="${MOONCAKE_STORE_THREADS:-4}"

# Required by start_lmcache_mp.sh on every vLLM requester host/Pod. This is the
# routable control endpoint advertised to P2PHANDSHAKE, not an HCA device name.
export MOONCAKE_REQUESTER_HOST="${MOONCAKE_REQUESTER_HOST:-}"

export LONGQA_DOCUMENT_LENGTH="${LONGQA_DOCUMENT_LENGTH:-10000}"
export LONGQA_NUM_DOCUMENTS="${LONGQA_NUM_DOCUMENTS:-20}"
export LONGQA_OUTPUT_LEN="${LONGQA_OUTPUT_LEN:-2}"
export LONGQA_REPEAT_COUNT="${LONGQA_REPEAT_COUNT:-1}"
export LONGQA_REPEAT_MODE="${LONGQA_REPEAT_MODE:-tile}"
export LONGQA_MAX_INFLIGHT="${LONGQA_MAX_INFLIGHT:-1}"
export LONGQA_SHUFFLE_SEED="${LONGQA_SHUFFLE_SEED:-0}"
export LONGQA_SLEEP_AFTER_WARMUP="${LONGQA_SLEEP_AFTER_WARMUP:-15}"
